### ISSUE TITLE
Works Perfect. But how to get Travel Time

### ISSUE THREAD

**Issue by sivabe35** [akexorcist/Android-GoogleDirectionLibrary#12]

**Comment by akexorcist** [comment]
You can get total travel time from each leg (Any route may have more than one way. Each way it's called leg) by
`Info distanceInfo = leg.getDistance();
Info durationInfo = leg.getDuration();
String distance = distanceInfo.getText();
String duration = durationInfo.getText();`

I already described in this article : http://www.akexorcist.com/2015/12/google-direction-library-for-android-en.html

**Comment by sivabe35** [comment]
akexorcist thank you so much :)
