### ISSUE TITLE
problem with dependencies

### ISSUE THREAD

**Issue by msroid** [akexorcist/Android-GoogleDirectionLibrary#13]
hi
about one month ago i add this library to my project and it was really good and everything was ok.
but now i don't know what is changed but there are several issues with dependencies (retrofit, okhttp, parceler and etc)
it says failed to resolve those dependencies.
please guide me what i have to do.

thanks for your help

**Comment by akexorcist** [comment]
I fix about retrofit dependencies. please update and check again in soon (maybe next 6 hours)

**Comment by msroid** [comment]
really thanks now everything is ok.

**Comment by vaniakerer** [comment]
Hi, I encountered the same problem on the version 1.1.0. 
How can I fix it? 

thanks.
