### ISSUE TITLE
dependencies problem

### ISSUE THREAD

**Issue by shern91** [akexorcist/Android-GoogleDirectionLibrary#15]
Hi, i was following your tutorial [this](http://www.akexorcist.com/2015/12/google-direction-library-for-android-en.html) and github here. But when i try to run my gradle build have some error

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.

> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/gson/annotations/Expose.class

but after i remove the "compile 'com.akexorcist:googledirectionlibrary:1.0.4'" and your code it was back to normal. How should i solve this?

Thank in advance

**Comment by akexorcist** [comment]
@shern91 I fixed this problem in version 1.0.5. 

Thank you for your feedback
