### ISSUE TITLE
Manifest Merger failed

### ISSUE THREAD

**Issue by Aastha77Gupta** [akexorcist/Android-GoogleDirectionLibrary#16]
HI,

I am getting the error 
Error:Execution failed for task ':app:processDebugManifest'.
​​

> Manifest merger failed : uses-sdk:minSdkVersion 10 cannot be smaller than version 14 declared in library [com.akexorcist:googledirectionlibrary:1.0.4] /Users/agupta/AndroidStudioProjects/DirectionsApp/app/build/intermediates/exploded-aar/com.akexorcist/googledirectionlibrary/1.0.4/AndroidManifest.xml
>     Suggestion: use tools:overrideLibrary="com.akexorcist.googledirection" to force usage

I added <uses- sdk tools:overrideLibrary="com.akexorcist.googledirection"> in the manifest file to override. 
Still getting the same error. 
Please advise.

Thank You!

**Comment by akexorcist** [comment]
@Aastha77Gupta  Sorry guy, but my library is run with minimum SDK version at least API 14
