### ISSUE TITLE
directionPositionList null

### ISSUE THREAD

**Issue by I-CX** [akexorcist/Android-GoogleDirectionLibrary#17]
Hi, i was using this lib for a few days now and i realized that i can't draw routes anymore, after debugging i noticed that directionPositionList is empty. Any help please

![image](https://cloud.githubusercontent.com/assets/17389813/16347610/3baafe20-3a3d-11e6-80a2-69c77e2b550d.png)

**Comment by AlburIvan** [comment]
I too can't seem to draw routes anymore and I have this error

`
E/Volley: [155] hj.a: Unexpected response code 400 for https://clients4.google.com/glm/mmap/api
D/Volley: [154] hj.a: HTTP response for request=<[ ] https://clients4.google.com/glm/mmap/api 0x99e6744e NORMAL 95> [lifetime=12072], [size=145], [rc=400], [retryCount=1]
D/Volley: [1] gu.b: 12074 ms: [ ] https://clients4.google.com/glm/mmap/api 0x99e6744e NORMAL 95`

**Comment by I-CX** [comment]
I solved my problem by changing the Google ServerKey i was using, check
that out

2016-07-02 16:02 GMT+00:00 Ivan Alberto <notifications@github.com>:
