### ISSUE TITLE
Leg.getDirectionPoint() returns inconsistent point list

### ISSUE THREAD

**Issue by Akkell** [akexorcist/Android-GoogleDirectionLibrary#2]
Returned point list from Leg.getDirectionPoint() contains "duplicated" points: point + the same point with higher precision. This results in the Polyline artifacts. See the screenshots:
![1](https://cloud.githubusercontent.com/assets/7806442/11689737/ecea1d8a-9e9b-11e5-9649-113b2cba6dbd.png)
![2](https://cloud.githubusercontent.com/assets/7806442/11689738/eceb44f8-9e9b-11e5-9a44-1c9f9ad4d979.png)

I believe this is caused by the method DirectionConverter.convertStepToPosition()

    private static void convertStepToPosition(Step step, ArrayList<LatLng> directionPointList) {
        // Get start location
        directionPointList.add(step.getStartLocation().getCoordination()); //point duplication

        // Get encoded points location
        if (step.getPolyline() != null) {
            ArrayList<LatLng> decodedPointList = step.getPolyline().getPointList();
            if (decodedPointList != null && decodedPointList.size() > 0) {
                for (LatLng position : step.getPolyline().getPointList()) {
                    directionPointList.add(position);
                }
            }
        }

        // Get end location
        directionPointList.add(step.getEndLocation().getCoordination()); //point duplication
    }

Which results in point list that looks like:
 lat/lng: (-33.88001**44**,151.2100**253**),
 lat/lng: (-33.88001,151.21003),
 lat/lng: (-33.88019,151.20988),
 lat/lng: (-33.8801**877**,151.20988**22**),
 lat/lng: (-33.8801**877**,151.20988**22**),
 lat/lng: (-33.88019,151.20988),
...

Code:

        final LatLng origin = new LatLng(-33.88, 151.21);
        final LatLng destination = new LatLng(origin.latitude - 0.01, origin.longitude - 0.01);

        GoogleDirection.withServerKey("")
                .from(origin)
                .to(destination)
                .transportMode(TransportMode.DRIVING)
                .execute(new DirectionCallback() {
                    @Override
                    public void onDirectionSuccess(Direction direction) {

                        if (direction.isOK()) {
                            googleMap.addMarker(new MarkerOptions().position(origin));
                            googleMap.addMarker(new MarkerOptions().position(destination));

                            ArrayList<LatLng> directionPositionList = direction.getRouteList().get(0).getLegList().get(0).getDirectionPoint();
                            googleMap.addPolyline(DirectionConverter.createPolyline(mapView.getContext(), directionPositionList, 5, Color.RED));
                        } else {
                            
                        }
                    }

                    @Override
                    public void onDirectionFailure(Throwable t) {

                    }
                });

Thank you for handy library!

**Comment by akexorcist** [comment]
Thank you. I will fix this problem in soon.

**Comment by negrova** [comment]
hello, I have a problem in the following line: He tells me error mapView

googleMap.addPolyline(DirectionConverter.createPolyline(mapView.getContext(), directionPositionList, 5, Color.RED));

**Comment by akexorcist** [comment]
@negrova  Please create new issue about your problem and tell me more about your error. It great  if you show your error log from LogCat.

**Comment by akexorcist** [comment]
@Akkell That isn't problem about duplicated points. But the problem is caused by the point that sent from server is inconsistent point. 

<img width="316" alt="screen shot 2559-03-08 at 03 31 51" src="https://cloud.githubusercontent.com/assets/1949576/13582806/e4d9a0da-e4e0-11e5-9963-0b0c15a1f0aa.png">

**Comment by ValeFCF** [comment]
Any solution for this?
Before, I using another library and the server points were OK.

another library:
[lat/lng: (19.43854,-99.20259), lat/lng: (19.43856,-99.20294), lat/lng: (19.43857,-99.20316), lat/lng: (19.4386,-99.20395), lat/lng: (19.4386,-99.20395), lat/lng: (19.43852,-99.20395), lat/lng: (19.43855,-99.20442), lat/lng: (19.43859,-99.20532), lat/lng: (19.43864,-99.20654), lat/lng: (19.43869,-99.20776), lat/lng: (19.43869,-99.20797), lat/lng: (19.4387,-99.20819), lat/lng: (19.43873,-99.20886), lat/lng: (19.43873,-99.20899), lat/lng: (19.43875,-99.20931), lat/lng: (19.43877,-99.20987), lat/lng: (19.43875,-99.21001), lat/lng: (19.43878,-99.21061), lat/lng: (19.43883,-99.21182), lat/lng: (19.43883,-99.21182), lat/lng: (19.43894,-99.21183), lat/lng: (19.43895,-99.21208), lat/lng: (19.43896,-99.21235), lat/lng: (19.43901,-99.21353), lat/lng: (19.43903,-99.2137), lat/lng: (19.43905,-99.2139), lat/lng: (19.43905,-99.21393), lat/lng: (19.43906,-99.21395), lat/lng: (19.43906,-99.21396), lat/lng: (19.43907,-99.21398), lat/lng: (19.43908,-99.21399), lat/lng: (19.43908,-99.21401), lat/lng: (19.4391,-99.21404), lat/lng: (19.4391,-99.21407), lat/lng: (19.4391,-99.21408), lat/lng: (19.4391,-99.21413), lat/lng: (19.4391,-99.21413), lat/lng: (19.43922,-99.21416), lat/lng: (19.43931,-99.2142), lat/lng: (19.43936,-99.21422), lat/lng: (19.43952,-99.2143), lat/lng: (19.4407,-99.21493), lat/lng: (19.44107,-99.21512), lat/lng: (19.44121,-99.21519), lat/lng: (19.44162,-99.2154), lat/lng: (19.44185,-99.21552), lat/lng: (19.44196,-99.21559), lat/lng: (19.44203,-99.21564), lat/lng: (19.44203,-99.21564), lat/lng: (19.44218,-99.21576), lat/lng: (19.44228,-99.21586), lat/lng: (19.44237,-99.21595), lat/lng: (19.44245,-99.21603), lat/lng: (19.44283,-99.21637), lat/lng: (19.44312,-99.21662), lat/lng: (19.44325,-99.21674), lat/lng: (19.44338,-99.21682), lat/lng: (19.4436,-99.21693), lat/lng: (19.44406,-99.21715), lat/lng: (19.44412,-99.21718), lat/lng: (19.4442,-99.21725), lat/lng: (19.4442,-99.21725), lat/lng: (19.44451,-99.21736), lat/lng: (19.44451,-99.21736), lat/lng: (19.44455,-99.21746), lat/lng: (19.44457,-99.21748), lat/lng: (19.44458,-99.21752), lat/lng: (19.44458,-99.21755), lat/lng: (19.44458,-99.2176), lat/lng: (19.44458,-99.21763), lat/lng: (19.44458,-99.21766), lat/lng: (19.44456,-99.21772), lat/lng: (19.44449,-99.21778), lat/lng: (19.44444,-99.21782), lat/lng: (19.44442,-99.21785), lat/lng: (19.44439,-99.21789), lat/lng: (19.44439,-99.21789), lat/lng: (19.44438,-99.21795), lat/lng: (19.44437,-99.21799), lat/lng: (19.44437,-99.218), lat/lng: (19.44437,-99.21804), lat/lng: (19.44438,-99.21807), lat/lng: (19.44438,-99.21809), lat/lng: (19.44439,-99.2181), lat/lng: (19.44441,-99.21816), lat/lng: (19.44443,-99.21821), lat/lng: (19.44448,-99.21831), lat/lng: (19.44453,-99.21843), lat/lng: (19.4446,-99.21857), lat/lng: (19.44469,-99.21875), lat/lng: (19.44478,-99.21895), lat/lng: (19.44485,-99.21908), lat/lng: (19.4449,-99.21917), lat/lng: (19.44497,-99.21928), lat/lng: (19.44502,-99.21935), lat/lng: (19.44509,-99.21942), lat/lng: (19.44515,-99.21949), lat/lng: (19.44523,-99.21957), lat/lng: (19.44531,-99.21964), lat/lng: (19.4454,-99.2197), lat/lng: (19.44549,-99.21977), lat/lng: (19.44557,-99.21981), lat/lng: (19.44566,-99.21986), lat/lng: (19.44576,-99.2199), lat/lng: (19.44579,-99.21992), lat/lng: (19.44591,-99.21995), lat/lng: (19.44603,-99.21999), lat/lng: (19.44616,-99.22001), lat/lng: (19.44625,-99.22002), lat/lng: (19.44635,-99.22003), lat/lng: (19.44646,-99.22002), lat/lng: (19.44667,-99.22002), lat/lng: (19.44689,-99.22001), lat/lng: (19.44721,-99.22), lat/lng: (19.44749,-99.22), lat/lng: (19.44792,-99.21999), lat/lng: (19.44808,-99.22), lat/lng: (19.44839,-99.22), lat/lng: (19.44896,-99.21999), lat/lng: (19.44905,-99.21999), lat/lng: (19.44919,-99.21999), lat/lng: (19.44921,-99.21999), lat/lng: (19.44951,-99.21998), lat/lng: (19.44964,-99.21999), lat/lng: (19.44993,-99.21997), lat/lng: (19.45017,-99.21995), lat/lng: (19.45029,-99.21994), lat/lng: (19.4504,-99.21994), lat/lng: (19.45107,-99.21988), lat/lng: (19.45107,-99.21988), lat/lng: (19.45118,-99.21991), lat/lng: (19.4513,-99.21992), lat/lng:
05-29 23:02:52.054 14531-14531......


Android-GoogleDirectionLibrary:
[lat/lng: (19.4385434,-99.2025889), lat/lng: (19.438540000000003,-99.20259000000001), lat/lng: (19.438560000000003,-99.20294000000001), lat/lng: (19.438570000000002,-99.20316000000001), lat/lng: (19.4386,-99.20395), lat/lng: (19.4386045,-99.2039454), lat/lng: (19.4386045,-99.2039454), lat/lng: (19.4386,-99.20395), lat/lng: (19.43852,-99.20395), lat/lng: (19.438550000000003,-99.20442000000001), lat/lng: (19.43859,-99.20532000000001), lat/lng: (19.438640000000003,-99.20654), lat/lng: (19.43869,-99.20776000000001), lat/lng: (19.43869,-99.20797), lat/lng: (19.4387,-99.20819), lat/lng: (19.438730000000003,-99.20886), lat/lng: (19.438730000000003,-99.20899000000001), lat/lng: (19.438750000000002,-99.20931), lat/lng: (19.43877,-99.20987000000001), lat/lng: (19.438750000000002,-99.21001000000001), lat/lng: (19.43878,-99.21061), lat/lng: (19.438830000000003,-99.21182), lat/lng: (19.4388294,-99.2118232), lat/lng: (19.4388294,-99.2118232), lat/lng: (19.438830000000003,-99.21182), lat/lng: (19.438940000000002,-99.21183), lat/lng: (19.438950000000002,-99.21208000000001), lat/lng: (19.43896,-99.21235000000001), lat/lng: (19.439010000000003,-99.21353), lat/lng: (19.439030000000002,-99.2137), lat/lng: (19.43905,-99.21390000000001), lat/lng: (19.43905,-99.21393), lat/lng: (19.43906,-99.21395000000001), lat/lng: (19.43906,-99.21396000000001), lat/lng: (19.43907,-99.21398), lat/lng: (19.43908,-99.21399000000001), lat/lng: (19.43908,-99.21401), lat/lng: (19.4391,-99.21404000000001), lat/lng: (19.4391,-99.21407), lat/lng: (19.4391,-99.21408000000001), lat/lng: (19.4391,-99.21413000000001), lat/lng: (19.4391043,-99.2141271), lat/lng: (19.4391043,-99.2141271), lat/lng: (19.4391,-99.21413000000001), lat/lng: (19.439220000000002,-99.21416), lat/lng: (19.439310000000003,-99.2142), lat/lng: (19.43936,-99.21422000000001), lat/lng: (19.43952,-99.21430000000001), lat/lng: (19.440700000000003,-99.21493000000001), lat/lng: (19.44107,-99.21512000000001), lat/lng: (19.44121,-99.21519), lat/lng: (19.44162,-99.2154), lat/lng: (19.441850000000002,-99.21552000000001), lat/lng: (19.44196,-99.21559), lat/lng: (19.442030000000003,-99.21564000000001), lat/lng: (19.4420257,-99.2156369), lat/lng: (19.4420257,-99.2156369), lat/lng: (19.442030000000003,-99.21564000000001), lat/lng: (19.44218,-99.21576), lat/lng: (19.44228,-99.21586), lat/lng: (19.44237,-99.21595), lat/lng: (19.44245,-99.21603), lat/lng: (19.44283,-99.21637000000001), lat/lng: (19.44312,-99.21662), lat/lng: (19.443250000000003,-99.21674), lat/lng: (19.44338,-99.21682000000001), lat/lng: (19.4436,-99.21693), lat/lng: (19.44406,-99.21715), lat/lng: (19.44412,-99.21718000000001), lat/lng: (19.444200000000002,-99.21725), lat/lng: (19.4442017,-99.21725359999999), lat/lng: (19.4442017,-99.21725359999999), lat/lng: (19.444200000000002,-99.21725), lat/lng: (19.44451,-99.21736000000001), lat/lng: (19.4445078,-99.21736), lat/lng: (19.4445078,-99.21736), lat/lng: (19.44451,-99.21736000000001), lat/lng: (19.444550000000003,-99.21746), lat/lng: (19.444570000000002,-99.21748000000001), lat/lng: (19.444580000000002,-99.21752000000001), lat/lng: (19.444580000000002,-99.21755), lat/lng: (19.444580000000002,-99.2176), lat/lng: (19.444580000000002,-99.21763000000001), lat/lng: (19.444580000000002,-99.21766000000001), lat/lng: (19.444560000000003,-99.21772000000001), lat/lng: (19.444490000000002,-99.21778), lat/lng: (19.44444,-99.21782), lat/lng: (19.44442,-99.21785000000001), lat/lng: (19.444390000000002,-99.21789000000001), lat/lng: (19.4443855,-99.2178948), lat/lng: (19.4443855,-99.2178948), lat/lng: (19.444390000000002,-99.21789000000001), lat/lng: (19.444380000000002,-99.21795), lat/lng: (19.444370000000003,-99.21799000000001), lat/lng: (19.444370000000003,-99.218), lat/lng: (19.444370000000003,-99.21804), lat/lng: (19.444380000000002,-99.21807000000001), lat/lng: (19.444380000000002,-99.21809), lat/lng: (19.444390000000002,-99.2181), lat/lng: (19.44441,-99.21816000000001), lat/lng: (19.44443,-99.21821000000001), lat/lng: (19.444480000000002,-99.21831), lat/lng: (19.44453,-99.21..............
