### ISSUE TITLE
project not building with firebase

### ISSUE THREAD

**Issue by nishantpardamwar** [akexorcist/Android-GoogleDirectionLibrary#22]
cant build my project if firebase messaging lib is also there in build.gradle with this library

my current setup has play service version 37 and google repository version 38

but it was working with with version 36 but now it is not building

im getting this error

> Error:Error converting bytecode to dex:
> Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ItemListIntents;

and even if i include multidex support i get error

> Error:Execution failed for task ':app:transformClassesWithJarMergingForKioskModeUat'.
> > com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/android/gms/actions/ItemListIntents.class

build.gradle 

```
.
.
 dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile('com.mikepenz:materialdrawer:5.6.0@aar') {
        transitive = true
    }
    compile('com.crashlytics.sdk.android:crashlytics:2.6.5@aar') {
        transitive = true;
    }
    compile 'jp.wasabeef:recyclerview-animators:2.2.4'
    compile 'com.michaelpardo:activeandroid:3.1.0-SNAPSHOT'
    compile 'com.android.support:design:24.2.1'
    compile 'com.android.support:cardview-v7:24.2.1'
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'org.greenrobot:eventbus:3.0.0'
    compile 'com.makeramen:roundedimageview:2.2.0'
    compile 'com.weiwangcn.betterspinner:library:1.1.0'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.okhttp3:okhttp-urlconnection:3.4.1'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.4.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.github.johnkil.android-robototextview:robototextview:2.5.0'
    compile 'com.google.firebase:firebase-messaging:9.6.1'
    compile 'com.akexorcist:googledirectionlibrary:1.0.4'
}
.
.

```

**Comment by akexorcist** [comment]
@nishantpardamwar It might be about the version of base google play services library in my library and fire messaging library are different.

But my library doesn't use it (Need only LatLng class), so I already excluded it in 1.0.5. This would solved your problem.

Thank you for your feedback
