### ISSUE TITLE
Cancel Connection, and dismiss callback

### ISSUE THREAD

**Issue by shkhaksar** [akexorcist/Android-GoogleDirectionLibrary#24]
This is a really simple library, but it don't have a function for cancelling direction request when activity getting paused.

**Comment by akexorcist** [comment]
I just added it in v1.1.0. Sorry for take very long time to support this feature.

```java
DirectionTask task = GoogleDirection.withServerKey(serverKey)
        .from(origin)
        .to(destination)
        .transportMode(TransportMode.DRIVING)
        .execute(this);

...

if (!task.isFinished()) {
    task.cancel();
}
```

DirectionTask based from Call in Retrofit 2. So you can get Call by
```java
Call<Direction> call = task.toRetrofitCall();
```
