### ISSUE TITLE
How to get waypoint_order using this............?????

### ISSUE THREAD

**Issue by anupkumar1234** [akexorcist/Android-GoogleDirectionLibrary#26]
Thanks Akexorcist..... This is very very useful for me showing waypoints after latest commit.......

And My question is that how to get waypoint_order through this API.......

Thanks in Advance.......

**Comment by akexorcist** [comment]
Check out v1.1.0! You can get waypoint_order in Route with getWaypointOrderList()

```java
Route route = direction.getRouteList().get(0);
List<Integer> waypointOrderList = route.getWaypointOrderList();
```
