### ISSUE TITLE
Support text address instead of LatLng

### ISSUE THREAD

**Issue by ahetawal-p** [akexorcist/Android-GoogleDirectionLibrary#27]
Hello, 
I see the google api support `origin` and `destination` as text then just the `LatLng`.

[Request Params](https://developers.google.com/maps/documentation/directions/intro#RequestParameters)

Is there any plan to support the text version also, since most of my addresses are in plain text.

**Comment by sagar-bhatt** [comment]
@ahetawal-p

You can use `GeoCoder` inbuilt class to convert text address to `LatLng` and vice versa.
Sample:
```
Geocoder geocoder = new Geocoder(getContext());
List<Address> addresses = null;
try {
		// Getting a maximum of 3 Address that matches the input
		addresses = geocoder.getFromLocationName(textAddress, 3);
		if (addresses != null && !addresses.equals("")){
			// Get the first address
			Address address = (Address) addresses.get(0);
			latitude = address.getLongitude();
			longitude = address.getLatitude();
			LatLng latLng = new LatLng(address.getLatitude(), address.getLongitude());
			// do something here
		}
} catch (Exception e) {}
```
Hope this helps.

Best,
Sagar

**Comment by akexorcist** [comment]
As @sagar-bhatt said. You have to do Geocoder by your own code.
