### ISSUE TITLE
NPE on DirectionConverter class

### ISSUE THREAD

**Issue by nekooei** [akexorcist/Android-GoogleDirectionLibrary#28]
Hello bro.
i use you library in my application and my application crashes on your 

> DirectionConverter

 class in method `dptopx` in line **130** causes NullPointerException
if you like i can help you in this Issue or other Issues
our user have android 5 client

**Comment by akexorcist** [comment]
Are your sure that doesn't because the context is null?

**Comment by khizar1556** [comment]
it exist again and again please resolve this issue i am using 1.1.1 version of your liberary problem is still exist
