### ISSUE TITLE
Where i find Server APi Key

### ISSUE THREAD

**Issue by ShubhamSanware** [akexorcist/Android-GoogleDirectionLibrary#32]
Can you plz tell me.. from where I got the server API key

**Comment by sagar-bhatt** [comment]
Hello Shubham,

Visit Google Maps Directions API documentation page, [click here](https://developers.google.com/maps/documentation/directions/get-api-key)

Click on the button named,
> GET A KEY

select your project from the drop down and Enable API. You're all set!

**Note**: You need to log in to your google account to generate the API key.

Best,
Sagar

**Comment by rajitbansal** [comment]
Its API key but as he told Key for Server is different?
