### ISSUE TITLE
Why is minimum SDK version 14?

### ISSUE THREAD

**Issue by saqada** [akexorcist/Android-GoogleDirectionLibrary#38]
Hi, guys. 

Sorry, if I ask improper question, but I really can't understand why the library needs API version 14 or more. Google maps are available from API 11. I changed minimum SDK version to 11, compiled successfully and used to some extend the library. What causes the reason to use higher API? 

Regards,
SaQada

**Comment by akexorcist** [comment]
Nothing, just though about no device that running on pre-ICS can install latest google play services and app without full storage.
