### ISSUE TITLE
Error:(62, 44) error: cannot access AbstractSafeParcelable class file for com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable not found

### ISSUE THREAD

**Issue by basmasrour** [akexorcist/Android-GoogleDirectionLibrary#39]
After adding this lib. I got this error, Is there any conflict?
Error:(62, 44) error: cannot access AbstractSafeParcelable
class file for com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable not found

**Comment by akexorcist** [comment]
I think maybe the conflict from Google Play Services. Just exclude the Google Play Services dependencies in this library and use your own.
