### ISSUE TITLE
Alternate direction are not showing?

### ISSUE THREAD

**Issue by ravigupta9363** [akexorcist/Android-GoogleDirectionLibrary#4]

**Comment by ravigupta9363** [comment]
Alternate direction are showing with same color as main route color I have set in map, how to show them with different color

**Comment by akexorcist** [comment]
Follow this, 
https://github.com/akexorcist/Android-GoogleDirectionLibrary/blob/master/app/src/main/java/com/akexorcist/googledirection/sample/AlternativeDirectionActivity.java
