### ISSUE TITLE
 Multiple dex files define Lcom/google/maps/android/BuildConfig;

### ISSUE THREAD

**Issue by albert0m** [akexorcist/Android-GoogleDirectionLibrary#46]
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/maps/android/BuildConfig;

This happens when the library google-maps-utils is used.

```
  implementation project(':google-maps-utils')
    compile 'com.akexorcist:googledirectionlibrary:1.1.1'
```

**Comment by akexorcist** [comment]
Which version of google-maps-utils library? To make sure, you should import the google-maps-utils directly from JCenter 

```
implementation 'com.google.maps.android:android-maps-utils:0.5'
```

This google-maps-utils version should work fine with my library, It's same version (v0.5)

Other way, exclude the google-maps-utils in my library
```
implementation ('com.akexorcist:googledirectionlibrary:1.1.1') {
	exclude module: 'google-maps-utils'
}
```
