### ISSUE TITLE
signed release app crashes in the direction fragment

### ISSUE THREAD

**Issue by takmilul** [akexorcist/Android-GoogleDirectionLibrary#47]
after creating a signed apk, when i click the direction button to show the direction in a fragment it shows error like **`onDirectionSuccess(unknown sources)`** but in debugging mode it works fine.
please help me....

**Comment by akexorcist** [comment]
Did you added the ProGuard rules for this library?

## ProGuard
```
-keep class com.google.android.gms.maps.** { *; }
-keep interface com.google.android.gms.maps.* { *; }

-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keepattributes Signature
-keepattributes Exceptions

-keepclasseswithmembers class * {
    @retrofit2.http.* <methods>;
}
```

**Comment by MeenuBabu** [comment]
For anyone who had stumbled across this issue, may have to add the below rule as well along with the mentioned proguard rules.
-keep class com.akexorcist.googledirection.model.** { *;}
