### ISSUE TITLE
Simple Direction app not drawing map but status is OK

### ISSUE THREAD

**Issue by Plaigon** [akexorcist/Android-GoogleDirectionLibrary#49]
Hi guys, i would like some help to fix my problem. I use your server api key but problem is still present.
Here is code: https://pastebin.com/uFSMG4GY
Thanks in advance!

**Comment by limpep** [comment]
You need to generate your own API key from https://console.developers.google.com.

**Comment by Plaigon** [comment]
I did, is the second key correct, that one i have to replace with the old one ?

**Comment by limpep** [comment]
What is the error you are getting? Can you past it here.

**Comment by Plaigon** [comment]
No more need to worry, problem is fixed, old key was replaced by new mine and that's fine henceforth =)
Thank you !
