### ISSUE TITLE
How to get Duration

### ISSUE THREAD

**Issue by mahesh517** [akexorcist/Android-GoogleDirectionLibrary#55]
Hi,
If i have waypoints means how to get duration between all locations

**Comment by akexorcist** [comment]
I added the total distance and duration in Route. 
https://github.com/akexorcist/Android-GoogleDirectionLibrary/commit/fa42e57d6ace382f3362931788a5598977ab9ba1

So you can get the total duration in seconds in the route.
```
Route route = ...
long totalDuration = route.getTotalDuration()
```
