### ISSUE TITLE
Not Showing direction

### ISSUE THREAD

**Issue by shreekant123** [akexorcist/Android-GoogleDirectionLibrary#61]
Hi...I am using this. it showing the status OK but not showing a path on map

**Comment by akexorcist** [comment]
Status OK mean you got the correctly response from the API but you have to check that response have any Latitude/Longitude data to make sure.

**Comment by maheshmnj** [comment]
@Override
`public void onDirectionSuccess(Direction direction) {
    String status = direction.getStatus();
    }
`
if the value of status is OK means route can be established within the two locations and you are good to go.
use this line of code to get the path 

`ArrayList<LatLng> directionPositionList = leg.getDirectionPoint();
PolylineOptions polylineOptions = DirectionConverter.createPolyline(this, directionPositionList, 5, Color.RED);`



follow this link for more 
googleMap.addPolyline(polylineOptions);

**Comment by sabu0balakrishnan** [comment]
ArrayList<LatLng> directionPositionList = leg.getDirectionPoint();

where i can get "leg"

**Comment by sesesmith30** [comment]
`Route route = direction.getRouteList().get(0);
Leg leg = route.getLegList().get(0);
`

that will give you **leg**
