### ISSUE TITLE
OVER_QUERY_LIMIT Error

### ISSUE THREAD

**Issue by maheshsystimanx** [akexorcist/Android-GoogleDirectionLibrary#68]
"You have exceeded your daily request quota for this API. If you did not set a custom daily request quota, verify your project has an active billing account: http://g.co/dev/maps-no-account",
1553171377.382 15145-15458/com.holidays.appleholidays D/OkHttp:    "routes" : [],
1553171377.382 15145-15458/com.holidays.appleholidays D/OkHttp:    "status" : "OVER_QUERY_LIMIT"

**Comment by vivkebics** [comment]
Hi,
It is not the problem with library. Becuase free api direction usage quota. Please have look at the quota limits. 
```https://developers.google.com/maps/premium/previous-licenses/articles/usage-limits```
