### ISSUE TITLE
Multiple Destination

### ISSUE THREAD

**Issue by ghost** [akexorcist/Android-GoogleDirectionLibrary#7]
Hi I saw the image example, there are more than 2 markers. I thought it can be multiple direction.
But when I'm trying Google direction, the builder could not call multiple `.to(...)`.

is it possible to add multiple direction with your API?

Really appreciate for your work.

**Comment by akexorcist** [comment]
It looks like too late for you but I will add this feature in soon. Thank you for your suggestion.

**Comment by akexorcist** [comment]
Check out v1.1.0!! Waypoints support now
