### ISSUE TITLE
KEEP GETING REQUEST DENIED 

### ISSUE THREAD

**Issue by IanLaFlair** [akexorcist/Android-GoogleDirectionLibrary#72]
Hello, pls help my i am keep getting request denied ? 
already regenerate the api key

**Comment by akexorcist** [comment]
Do you generate it as Web API Key in Google Cloud Platform Console?

The Direction API is only Web API. You have to generate the new one as Web API Key not Android API Key in Google Maps API for Android

**Comment by srikanthnama** [comment]
If I want to restrict the API key, how do I do that? any specific http referrers that I need to add?

**Comment by rania-bensakina** [comment]
I keep getting it too plz help

**Comment by akexorcist** [comment]
@srikanthnama This library use the web API (there's no SDK for mobile support). So you can't restricted the API request. For the security concern, don't keep the key in the project directly. Please provide some API for the key to use it after logged in.

**Comment by Collpool2019** [comment]
Hello, pls help my i am keep getting request denied ?

**Comment by Collpool2019** [comment]
@akexorcist please provide a detailed solution as I generated an API key with application restrictions=none and API restrictions = don't restrict API  but still it shows REQUEST_DENIED.
PLEASE HELP.

**Comment by Collpool2019** [comment]
@akexorcist IS GOOGLE BILLING ACCOUNT NECESSARY FOR USING YOUR THIS DIRECTIONS API

**Comment by akexorcist** [comment]
@CollPool2019 Yes, it is. Direction API is not free

**Comment by var2611** [comment]
Direction API call is limited to 1 Daily if there is no billing account.
When you attach billing account it's limit for free will be increased to 1000 per month.
