### ISSUE TITLE
retrofit lib issue

### ISSUE THREAD

**Issue by doc-rj** [akexorcist/Android-GoogleDirectionLibrary#8]
I'm having this problem with your lib dependencies: https://github.com/square/retrofit/issues/854

Can you update your retrofit to retrofit2, I think it will probably fix it:

compile 'com.squareup.retrofit2:retrofit:2.0.0-beta3'

**Comment by akexorcist** [comment]
Sorry for very lately update. But v1.0.4 is already update new retrofit 2.
