### ISSUE TITLE
REQUEST_DENIED

### ISSUE THREAD

**Issue by dmbuguah** [akexorcist/Android-GoogleDirectionLibrary#9]
Hi..keep on getting REQUEST_DENIED yet I have the API key right.
Thanks.

**Comment by tasosno1** [comment]
maybe the same issue i'm having, i just gave the demo App on the play store a go and im getting a blank map.  has google blocked or changed something?

**Comment by exequielc** [comment]
I  have the same error, I see the map, but the  onDirectionSuccess return this error REQUEST_DENIED

**Comment by Akariuz** [comment]
Same error here, i have used my API key in other library and it works, but in this one i always get REQUEST_DENIED.

if you culd help us, i think you had make a wonderful work with the library and the excellent documentation, thank you very much for you work. But i have this little problem.

**Comment by akexorcist** [comment]
Sorry everyone, I didn't add error message to check when got problem about request denied. I will add it in next version so you will can check about your problem. (Should be get update today)

**Comment by Akariuz** [comment]
Thank you for your fast answer, now i get the rawBody, and i get this: 
`{"error_message":"This IP, site or mobile application is not authorized to use this API key. Request received from IP address 187.189.154.107, with empty referer","routes":[],"status":"REQUEST_DENIED"}`

can you help me, i have no idea what this is or how to solve it.

**Comment by akexorcist** [comment]
@Akariuz Because you have accept connection only from 187.189.154.107 in your Google Developer Console. Android Device requests are come from anywhere so you don't have to restrict request connection.

<img width="642" alt="screen shot 2559-03-08 at 10 49 16" src="https://cloud.githubusercontent.com/assets/1949576/13591464/72bd0a9c-e51b-11e5-9bbc-84b1c18e5f4d.png">

**Comment by Akariuz** [comment]
Is all working now, thank you very much :+1:

**Comment by dmbuguah** [comment]
Thanks.

**Comment by abdelrahmana** [comment]
> @Akariuz Because you have accept connection only from 187.189.154.107 in your Google Developer Console. Android Device requests can come from anywhere so don't restrict request connection.
> 
> <img alt="screen shot 2559-03-08 at 10 49 16" width="642" src="https://cloud.githubusercontent.com/assets/1949576/13591464/72bd0a9c-e51b-11e5-9bbc-84b1c18e5f4d.png">

but this not working when project is live on play store
